version: '3'

networks:
  wapiti:
    external: false

services:
  drone-server:
    image: wardknight/wapiti-server:v1.7
    container_name: wapiti-server
    ports:
    - 8080:8080
    networks:
     - wapiti
    restart: always